from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import TextFormatter
from youtube_transcript_api.formatters import JSONFormatter


video_id = "Oa4G7reH6qw"

# # retrieve the available transcripts
# transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

# # iterate over all available transcripts
# for transcript in transcript_list:

#     # the Transcript object provides metadata properties
#     print(
#         transcript.video_id,
#         transcript.language,
#         transcript.language_code,
#         # whether it has been manually created or generated by YouTube
#         transcript.is_generated,
#         # whether this transcript can be translated or not
#         transcript.is_translatable,
#         # a list of languages the transcript can be translated to
#         transcript.translation_languages,
#     )

#     # fetch the actual transcript data
#     print(transcript.fetch())

#     # translating the transcript will return another transcript object
#     print(transcript.translate('en').fetch())

# # you can also directly filter for the language you are looking for, using the transcript list
# transcript = transcript_list.find_transcript(['de', 'en'])  

# # or just filter for manually created transcripts  
# transcript = transcript_list.find_manually_created_transcript(['de', 'en'])  

# # or automatically generated ones  
# transcript = transcript_list.find_generated_transcript(['de', 'en'])



######################################################
# Must be a single transcript.
transcript = YouTubeTranscriptApi.get_transcript(video_id)

jsonformatter = JSONFormatter()
textformatter = TextFormatter()

# .format_transcript(transcript) turns the transcript into a JSON string.
json_formatted = jsonformatter.format_transcript(transcript)
# text_formatted = textformatter.format_transcript(transcript)

# print(json_formatted)
# print(text_formatted)

# Now we can write it out to a file.
with open('fauna.json', 'w', encoding='utf-8') as json_file:
    json_file.write(json_formatted)

# Now should have a new JSON file that you can easily read back into Python.